# Generated by Django 5.2.6 on 2025-10-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_message_file_message_file_name_message_file_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file_size',
        ),
    ]
